#common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: NjA3NGNiNDdiYWQ2ZmZkZGVmNDJjZTQ4NzdhYTYxNzBkZWM3Y2M1NGMxN2VlNjI5ZDgwMDI3MjIzZmY5ZjliMTBkNDA0ODg3YmJiYWVkYzkxYWNhZTc5ZWQ5MTQ0MWUxYmJhYw==
  logging:
    logstash: # forward logs to ELK
      enabled: true
      host: jhipster-logstash
  metrics:
    logs: # report metrics in the logs
      enabled: true
      report-frequency: 60 # in seconds

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
